format = """
$username\
$hostname\
$localip\
$shlvl\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$docker_context\
$container\
$terraform\
$env_var\
$sudo\
$cmd_duration\
$line_break\
$status\
$shell\
$character"""

[username]
show_always = true
style_user = "bold purple"

[hostname]
ssh_symbol = ""

[character]
success_symbol = "[±](bold green)"
error_symbol = "[±](bold red)"
vicmd_symbol = "[±](bold green)"

[git_commit]
tag_symbol = " tag "

[git_status]
format = '([\[](bold green)[$conflicted$renamed]($style)$modified$untracked$staged$deleted$ahead_behind[\]](bold green)) '
ahead = "[>$count](bold red)"
behind = "[<$count](bold cyan)"
diverged = "<>"
renamed = "r"
deleted = "[-](bold red)"
stashed = "s"
staged = "[+](bold green)"
modified = "[m](bold yellow)"
untracked = "[u](bold red)"

[aws]
symbol = "aws "

[c]
symbol = "C "

[cobol]
symbol = "cobol "

[conda]
symbol = "conda "

[crystal]
symbol = "cr "

[cmake]
symbol = "cmake "

[daml]
symbol = "daml "

[dart]
symbol = "dart "

[deno]
symbol = "deno "

[dotnet]
symbol = ".NET "

[directory]
read_only = " ro"
truncation_length = 8
truncation_symbol = "…/"
truncate_to_repo = false
style = "bold yellow"

[docker_context]
symbol = "docker "

[elixir]
symbol = "exs "

[elm]
symbol = "elm "

[git_branch]
style = "bold cyan"
symbol = " "

[golang]
symbol = "go "

[hg_branch]
symbol = "hg "

[java]
symbol = "java "

[julia]
symbol = "jl "

[kotlin]
symbol = "kt "

[lua]
symbol = "lua "

[nodejs]
symbol = "nodejs "

[memory_usage]
symbol = "memory "

[nim]
symbol = "nim "

[nix_shell]
symbol = "nix "

[ocaml]
symbol = "ml "

[package]
symbol = "pkg "

[perl]
symbol = "pl "

[php]
symbol = "php "

[pulumi]
symbol = "pulumi "

[purescript]
symbol = "purs "

[python]
symbol = "py "

[raku]
symbol = "raku "

[ruby]
symbol = "rb "

[rust]
symbol = "rs "

[scala]
symbol = "scala "

[spack]
symbol = "spack "

[sudo]
symbol = "sudo "

[swift]
symbol = "swift "

